name: Action

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: env

      - name: Add comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=`gh pr list --head="${{ needs.preview.outputs.branch_name }}" --json number | jq '.[0].number'`
          gh pr comment $PR --body "Check the preview!"
          gh pr comment $PR --body "'`env`'"

