name: Multiple actions (group)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-preview-test]

jobs:
  never-run:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: fail
        run: exit 1

  always-fail:
    needs: [pre-always-success]
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  always-success:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: exit 0

  pre-always-success:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: exit 0

  notify-slack-if-failed:
    needs: [always-fail, always-success, never-run, pre-always-success]
    if: ${{ failure() }}
    uses: rodolfo3/test-gh-actions/.github/workflows/notify_slack.yaml@main
    with:
      title: "GitHub Action failed!"
      text: "The build or a check failed on the action.\n@channel, check it!"
      needs_data: ${{ toJson(needs) }}
    secrets:
      SLACK_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}

