### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: Dependabot PR Check
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR created by Dependabot"
