name: Dependabot response

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      usePrNumber:
        description: 'Use PR number instead of branch name'
        required: true
        default: 'true'

jobs:
  build-preview-nw-smb:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    steps:
      # Cancel previous runs from other actions in the same branch
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      # Get and expose the branch name in the branch_name GH variable to be used in other steps
      - name: Set branch name if workflow dispatch
        id: branch_name_from_workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "branch_name=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Get and expose the branch name in the branch_name GH variable to be used in other steps
      - name: Set branch name if pull request
        id: branch_name_from_pull_request
        if: github.event_name == 'pull_request'
        run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      # Generate the alias for the build (for out ticket PRs)
      - name: Set alias
        if: github.event.inputs.usePrNumber != 'true'
        run: |
          env
          echo "alias=preview-$(if [[ "$BRANCH_NAME" =~ [0-9] ]]; then echo "${BRANCH_NAME//[!0-9]/}"; else echo "${BRANCH_NAME//\//-}"; fi)" >> $GITHUB_ENV
        env:
          BRANCH_NAME: ${{ env.branch_name }}

      # Generate the alias for the build (dependabot PRs)
      - name: Set alias (dependabot)
        if: github.event.inputs.usePrNumber == 'true'
        run: |
          set -x
          set -e
          PR_NUMBER=`gh pr list --head="${{ env.branch_name }}" --json number | jq '.[0].number'`
          echo "alias=dependabot-${PR_NUMBER}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ env.branch_name }}

      # Netlify deploy. It includes the branch name in the message param.
      - name: Use alias
        run: echo $ALIAS
        # env:
        #   ALIAS: ${{ env.alias }}
