name: A job that always fails

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-preview-test]

jobs:
  always-fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  notify-slack-if-failed:
    needs: [always-fail]
    if: ${{ failure() }}
    uses: rodolfo3/test-gh-actions/.github/workflows/notify_slack.yaml@main
    with:
      title: "GitHub Action failed!"
      text: "The build or a check failed on the action.\n@channel, check it!"
      needs_data: ${{ toJson(needs) }}
    secrets:
      SLACK_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}

