name: Preflight

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize]
    permissions:
      contents: read
      metadata: read
      pull-requests: write
      statuses: write

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: env
