name: Comment on all experiment branches
on:
  workflow_dispatch:

jobs:
  comment:
    name: Add a comment
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: env
        run: env
      - name: List and add comment
        run: |
          env
          echo
          export GH_REPO=$GITHUB_REPOSITORY
          for i in `gh pr list --jq '.[] | select(.labels[].name == "experiment")' --json 'labels,number' | jq '.number'`
          do
            echo gh pr comment $i --body '/rebase'
            gh pr comment $i --body '/rebase'
          done
