name: Rebase all experiment PRs
on:
  workflow_dispatch:

jobs:
  comment:
    name: Add a comment
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: experiment
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: List and add comment
        run: |
          env
          set +e # avoid stoping on errors

          git config --global user.email "tech@fundera.com"
          git config --global user.name "Github Action"

          export GH_REPO=$GITHUB_REPOSITORY
          TO_REBASE=`gh pr list --jq '.[] | select(.labels[].name == "'${TAG_NAME}'")' --json 'labels,number,baseRefName,headRefName' | jq -r '. | {number,baseRefName,headRefName} | join(";")'`

          for i in $TO_REBASE
          do
            IFS=';' read -a data <<< $i
            PR=${data[0]}
            BASE=${data[1]}
            HEAD=${data[2]}

            echo "Rebasing PR #${PR} (${HEAD} on ${BASE})"

            git checkout $HEAD
            git rebase origin/$BASE

            if [ "$?" == "0" ]
            then
              echo 'Success. Forcing push'
              # git push -f
            else
              echo 'Error. Aborting'
              git rebase --abort
              gh pr edit $PR --add-label "rebase required"
              gh pr comment $PR --body 'Tried and failed to rebase.'
            fi

            echo
            echo
          done
