name: A job that always skips

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-preview-test]

jobs:
  never-run:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: fail
        run: exit 1

  run-if-failed:
    runs-on: ubuntu-latest
    needs: [never-run]
    if: ${{ failure() }}
    steps:
      # Checkout the current branch
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"

      - name: Cache node modules and yarn cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/yarn
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      # Install dependencies usign yarn.
      # Only runs if the Cache node modules is not hit (no changes made in dependencies).
      - name: Install dependencies
        if: steps.cache-node-modules-cypress.outputs.cache-hit != 'true'
        working-directory: ./
        run: yarn --frozen-lockfile

      - name: yarn cache dir
        run: yarn cache dir

      - name: debug env
        run: env

      - name: notify slack
        run: |
          node --unhandled-rejections=strict ./tools/slack-notification --json='
            {
              "title": "GitHub Action failded!",
              "text": "The build or the check failed for one or more steps.\n@channel check it, @please"
            }
          '
        env:
          SLACK_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
          NEEDS_RESULT: ${{ toJson(needs.*.result) }}
