name: Tag

on:
  workflow_dispatch:

jobs:
  add-git-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag deploy on git
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          TAG_PREFIX=release/`date +%Y-%m-%d`

          git config --global user.email "tech@fundera.com"
          git config --global user.name "Github Action"

          git fetch origin

          function buildtag()
          {
            TAG=$TAG_PREFIX
            if [ `git tag -l $TAG | wc -l` == "0" ]
            then
              echo "$TAG"
              return
            fi
            for i in {1..9}
            do
              TAG="${TAG_PREFIX}-${i}"
              if [ `git tag -l $TAG | wc -l` == "0" ]
              then
                echo "$TAG"
                return
              fi
            done
          }

          TAG=$(buildtag)

          git tag $TAG
          git push origin $TAG
